---
- hosts: all
  gather_facts: false

  vars:
    service_account: ansible
    generated_password: "{{ lookup('password', '/dev/null', seed=inventory_hostname) }}"

  tasks:
  - name: generate a password
    set_stats:
      data:
        service_account_password: "{{ generated_password }}"

  - name: change a password for a service account
    user:
      name: "{{ service_account }}"
      state: present
      password: "{{ generated_password | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}"
    become: true

